Language: 'English'
Bungee: false
SccIsActive: false
Mysql:
  Status: false
  Host: '127.0.0.1'
  Port: 3306
  DatabaseName: 'mydatabase'
  SSLEnabled: false
  AutoReconnect: true
  VerifyServerCertificate: false
  User: 'admin'
  Password: 'not_0123456789'
  TableNameI: 'afkrecordPlayerData'
  TableNameII: 'afkrecordDateList'
General:
  SoftSaveInSeconds: 60
  MysqlSaveInSeconds: 600
  AfkCheckerInSeconds: 300
  AfkAfterInSeconds: 900
  TopListRefresh: 60
  
# DO NOT CHANGE THINGS BELOW!
# => <origin+message>~click@SUGGEST_COMMAND@/blubb~hover@SHOW_TEXT@messagepath
# => click@SUGGEST_COMMAND@/blubb
# => hover@SHOW_TEXTt@textpath
Identifier:
  Click: 'click'
  Hover: 'hover'
Seperator:
  BetweenFunction: '~'
  WhithinFuction: '@'
  Space: '+'
  HoverNewLine: '~!~'