name: AfkRecord
main: main.java.de.avankziar.afkrecord.spigot.AfkRecord
version: 1
author: Avankziar
website: https://www.spigotmc.org/resources/authors/avankziar.332028/
load: STARTUP
description: Afk Tracker Plugin
commands:
  afk:
    description: A Afk Command
  afkrecord:
    description: A Afkrecord
    aliases: [afkr]