name: AfkRecord
main: main.java.de.avankziar.afkrecord.spigot.AfkRecord
version: 8
author: Avankziar
website: https://www.spigotmc.org/resources/authors/avankziar.332028/
api-version: 1.16
description: Afk Tracker Plugin
softdepend: [Vault]