name: AfkRecord
main: main.java.de.avankziar.afkrecord.spigot.AfkRecord
version: 10
author: Avankziar
website: https://www.spigotmc.org/resources/authors/avankziar.332028/
api-version: 1.19
description: Afk Tracker Plugin
softdepend: [Vault, PlaceholderAPI, InterfaceHub]